# Generated by Django 3.0.2 on 2020-04-03 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetellerDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neteller_ID', models.CharField(max_length=20)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Deposite', models.CharField(max_length=50)),
                ('Profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NetellerSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neteller_ID', models.CharField(max_length=20)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Partner_code', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SkrillDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neteller_ID', models.CharField(max_length=20)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Deposite', models.CharField(max_length=50)),
                ('Profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SkrillSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neteller_ID', models.CharField(max_length=20)),
                ('Site_ID', models.CharField(max_length=50)),
                ('Partner_code', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agents_name', models.CharField(max_length=100)),
                ('agents_email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('Submited_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=100)),
                ('work_place', models.CharField(max_length=100)),
                ('author_description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
