# Generated by Django 3.0.5 on 2020-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200403_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created', models.DateField()),
            ],
        ),
    ]
