# Generated by Django 3.0.5 on 2020-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20200405_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlist',
            name='phone',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
