# Generated by Django 3.0.5 on 2020-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentlist_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidassign',
            name='idsource',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
