# Generated by Django 2.2.12 on 2020-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_siteidassign_idsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlist',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='amount',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='deposit_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='membership_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='neteller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='partner_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='refferded_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='skrill_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentlist',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
