# Generated by Django 2.2.12 on 2020-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20200425_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentlist',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='agentlist',
            name='commission',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
