# Generated by Django 2.2.12 on 2020-04-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20200425_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAgentsCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('commission', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateField(verbose_name=datetime.datetime(2020, 4, 25, 16, 41, 16, 553762))),
                ('updated', models.DateField()),
            ],
        ),
    ]
