# Generated by Django 2.2.12 on 2020-04-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_allagentscommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allagentscommission',
            name='created',
        ),
    ]
