# Generated by Django 2.2.12 on 2020-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_remove_allagentscommission_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='netellerdeposit',
            name='AgentProfit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='netellerdeposit',
            name='AgentProfitType',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='skrilldeposit',
            name='AgentProfit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='skrilldeposit',
            name='AgentProfitType',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
