# Generated by Django 2.2.12 on 2020-04-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20200425_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='allagentscommission',
            name='applyrules',
            field=models.CharField(default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='netellerdeposit',
            name='AgentProfitType',
            field=models.CharField(default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='skrilldeposit',
            name='AgentProfitType',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
