# Generated by Django 2.2.12 on 2020-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20200425_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlist',
            name='commissionType',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
