# Generated by Django 2.2.12 on 2020-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentlist_commissiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlist',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
