# Generated by Django 2.2.12 on 2020-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_auto_20200425_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentlist',
            old_name='balance',
            new_name='balance_neteller',
        ),
        migrations.AddField(
            model_name='agentlist',
            name='balance_skrill',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
