# Generated by Django 2.2.12 on 2020-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_auto_20200426_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlist',
            name='balance_neteller',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agentlist',
            name='balance_skrill',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
