# Generated by Django 2.2.12 on 2020-04-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_auto_20200426_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlist',
            name='commission',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
