# Generated by Django 2.2.12 on 2020-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_auto_20200426_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentlist',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='agentlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
