# Generated by Django 2.2.12 on 2020-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_auto_20200426_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='netellersignup',
            name='VipStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skrillsignup',
            name='VipStatus',
            field=models.IntegerField(default=0),
        ),
    ]
