# Generated by Django 2.2.12 on 2020-04-26 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_auto_20200427_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 3, 52, 42, 943204)),
        ),
    ]
