# Generated by Django 2.2.12 on 2020-04-26 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_netellersignup_vipstatusdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skrilldeposit',
            old_name='Neteller_ID',
            new_name='Skrill_ID',
        ),
        migrations.RenameField(
            model_name='skrillsignup',
            old_name='Neteller_ID',
            new_name='Skrill_ID',
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 5, 18, 53, 499643)),
        ),
    ]
