# Generated by Django 2.2.12 on 2020-04-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_auto_20200429_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 22, 58, 27, 231272)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 22, 58, 27, 232271)),
        ),
    ]
