# Generated by Django 2.2.12 on 2020-05-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_auto_20200429_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='allagentscommission',
            name='adminCommissionIn1K',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 22, 33, 472169)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 22, 33, 472169)),
        ),
    ]
