# Generated by Django 2.2.12 on 2020-05-06 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_auto_20200507_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='netellerdeposit',
            name='AdminProfitIn1K',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='netellerdeposit',
            name='FinalCommssion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='skrilldeposit',
            name='AdminProfitIn1K',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='skrilldeposit',
            name='FinalCommssion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 36, 51, 256470)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 36, 51, 257471)),
        ),
    ]
