# Generated by Django 2.2.12 on 2020-05-06 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_auto_20200507_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlist',
            name='AdminProfitIn1K',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 44, 4, 913052)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 1, 44, 4, 915047)),
        ),
    ]
