# Generated by Django 2.2.12 on 2020-05-06 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_auto_20200507_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allagentscommission',
            name='RevShareAgent',
        ),
        migrations.RemoveField(
            model_name='allagentscommission',
            name='RevShareCB',
        ),
        migrations.AddField(
            model_name='agentlist',
            name='RevShareActDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 4, 51, 1, 459541)),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='RevShareAgent',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentlist',
            name='RevShareCB',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 4, 51, 1, 459541)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 4, 51, 1, 460536)),
        ),
    ]
