# Generated by Django 2.2.12 on 2020-05-07 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_auto_20200507_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetReceiables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('datecreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agentlist',
            name='RevShareActDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 7, 1, 34, 647292)),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 7, 1, 34, 647292)),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 7, 1, 34, 649288)),
        ),
    ]
