# Generated by Django 2.2.12 on 2020-05-09 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_auto_20200507_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlist',
            name='RevShareActDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 5, 22, 21, 491649)),
        ),
        migrations.AlterField(
            model_name='allagentscommission',
            name='activationDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 5, 22, 21, 491649)),
        ),
        migrations.AlterField(
            model_name='netellerdeposit',
            name='Deposite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='netellersignup',
            name='VipStatusDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 5, 22, 21, 491649)),
        ),
        migrations.AlterField(
            model_name='skrilldeposit',
            name='Deposite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
